= nShift Transsmart Developer Documentation
Copyright (C) {docyear} - Product Development - last updated: {docdate}
:doctype: book
:docinfo: shared,shared-head
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[introduction]
= Introduction
[%hardbreaks]
Being a developer documentation, the content of this document should primarily serve as the main guidance for those integrating Transsmart into their systems. This document is not meant to describe how Transsmart operates in the logistics process-chain, but rather assumes the reader to be familiar with the business operations of Transsmart, as an organization.

The purpose of this document is to be a sufficient guideline for integrating the Transsmart platform in the operations of another system.
[%hardbreaks]
Though the title of this document may imply that its target audience is developers, it actually is meant to be used by all system integrators that for one reason or the other may have an interest in the Transsmart integration capabilities. So system integrators, platform/solution architects and system developers, are all perceived as being the target audience of this document.
[%hardbreaks]
For any reader of this document, it should be possible to easily identify what the Transsmart integration platform has to offer, in terms of versioning and their respective supported resources.

The document references all publicly available environments, i.e. beta developments, user acceptance and production.

[integration_endpoints]
= Integration endpoints
Transsmart offers two integration endpoints:

* SOAP webservice
* RESTful API

The SOAP webservice is the longest-living integration endpoint of Transsmart.
link:docs/documentation_websvc_20210913.zip[*Download SOAP webservice documentation*]

The RESTful API has recently received a major upgrade in terms of features and capabilities.

*We advice you to integrate with our RESTful API because of the advantages of having more functionalities available*

[[restful_api]]
== Validation rules and directives
The API is offered as a RESTful web service. + 
The API assumes a plural-based resources naming convention.

=== Prerequisites
* A valid and active Transsmart account.
* A valid user attached to the Transsmart client account to be used.
* Basic knowledge of web-services (in particular RESTful services) and the HTTP protocol.
* Working knowledge of JSON or XML
* Familiarity with the logistics domain.

IMPORTANT: It is import to note that this document assumes certain technical knowledge on the part of the respective user, so it should not be mistaken for a user manual.

=== Environments

[width="100%",cols="3,3,4",options="header"]
|===
| Environment | Base URL | Description

| `BETA`
| https://beta-api.transsmart.com
| Available for (pilot) customers. Changes are deployed at least 1 week before being deployed to Accept.

| `ACCEPT`
| https://accept-api.transsmart.com
| Technically equal to Production except on deployment day (1 day difference); mainly used for implementations, validate new configurations and training.

| `PRODUCTION`
| https://api.transsmart.com
| Production environment
|===

=== Field changes
Developments are sometimes accompanied by the addition of new fields or changes to existing fields. When changing existing fields, we will make sure that they are backwards compatible and we will announce them well in advance through release notes. The addition of new fields has a shorter lead time; these changes will also be communicated via the release notes, but you should make the connection to us in such a way that no problems arise on your side when new, and therefore unknown to you, fields are added. These fields should be ignored or of course if desired, mapped to a corresponding field on your side.

[[overview-http-verbs]]
=== HTTP verbs
The API tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.

[width="100%",cols="3,10",options="header"]
|===
| Verb | Usage

| `GET`
| Mainly used to retrieve a resource though in some cases also trigger an action, for instance, in the case of document print.

| `POST`
| Used to create a new resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `PUT`
| Used to update an existing resource, full updates only

| `DELETE`
| Used to delete an existing resource
|===

[[overview-http-status-codes]]
=== HTTP status codes
The API tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.


[width="100%",cols="3,10",options="header"]
|===
| Status code | Usage

| `200 OK`
| Standard response for successful HTTP requests. The actual response will depend on the request method used. In a GET request, the response will contain an entity corresponding to the requested resource. In a POST request, the response will contain an entity describing or containing the result of the action.

| `201 Created`
| The request has been fulfilled and resulted in a new resource being created.

| `204 No Content`
| The server successfully processed the request, but is not returning any content.

| `400 Bad Request`
| The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

| `401 Unauthorized`
| The server cannot or will not process the request due a missing token or due to an invalid token.

| `404 Not Found`
| The requested resource could not be found but may be available again in the future. Subsequent requests by the client are permissible.

| `409 Conflict`
| Indicates that the request could not be processed because of conflict in the request, such as an 'add conflict' where a duplicated record is posted, the service returns then this code with a more detailed message.

| `415 Unsupported Media Type`
| The request entity has a media type which the server or resource does not support. For example, the client posts a request as text/plain, but the server requires that the post use a different format as to be aapplication/xml or application/json.

| `429 Too Many Requests`
| The user has sent too many requests in a given amount of time. Intended for use with rate-limiting schemes. See chapter 'Rate limiter' below for more information.

| `500 Internal Server Error`
| A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.
|===

=== Rate Limiter
To prevent our API from being overwhelmed, per API service type (shipment service, status service, report service etc…) we have configured rate limits per account per time frame. 

When high loads of calls are being done in a very short time frame, you will receive an 429 error. 

If that is the case, to avoid reaching our rate limiter, your configuration/integration needs to be verified by you or your (ERP/WMS) partner. 

Most probably the amount of calls can be reduced by lowering the configuration of sending API calls for (all) shipments.

The best way to implement a correct process for handling 429 errors, is to act on the information we send back in Response Header:

* X-RateLimit-Remaining: the number of remaining calls (if still allowed)
* X-RateLimit-Reset: the number of milliseconds before next call may be done (in case of a blocked call)

Two other ways are either simply wait longer before sending a retry or implement an exponential backoff which means you don’t retry sending a request for instance every 0.1 second but retry 1 second later, then 10 seconds later, then 1 minute later… etc. until you get the correct response call information.

NOTE: We comply with a Fair Use Policy and will adjust the values -and in exceptional cases even block requesters- if we notice there is abuse in submitting or requesting too much data.

=== Localization
For these three fields we comply with below applicable ISO codes: 


[width="100%",cols="3,10",options="header"]
|===
| Parameter | Description

| `language`
| ISO 639-1 two letter code in lower case.

| `country`
| ISO 3166-1 two letter code in upper case.

| `currency`
| ISO 4217 three letter code in upper case.
|===

=== Supported Data formats
Both JSON and XML are supported as input and output data formats.

NOTE: In the examples given in the resources' description only the json format is demonstrated.

=== MyTranssmart dashboard
In a nutshell: MyTranssmart is the dashboard which can be used to manage shipments. The dashboard is fully connected to our API backend, so all actions in the dashboard are done via API request calls and responses. When opening the Developer Tools in the internet browser, the Network tab will show wich Request URL is called when doing a specific action. This way you can understand in a more visual way which calls are being used for which purpose and which responses are given.

These are the URL's:

[width="100%",cols="3,10",options="header"]
|===
| Environment | URL

| `BETA`
| https://beta-my.transsmart.com/

| `ACCEPT`
| https://accept-my.transsmart.com/

| `PRODUCTION`
| https://my.transsmart.com/
|===


=== Direct links
The MyTranssmart dashboard supports direct links. These can be used to direct link from an ERP system to a specific page in the MyTranssmart dashboard: + 
`Path /v2/direct/details?key=cQBauM7gcQBauM7g...&reference=71117854` +
Note: key and reference in this example are not valid; you need a valid customer key and reference. Don’t forget to URL encode it as required for all query parameters. + 
See chapter 1.1 ‘Requesting for a token’ on how to obtain the required key. 

Options:

`/v2/direct/details?key=…&reference=…&account=…` +
`/v2/direct/overview?key=…` +
`/v2/direct/manifest?key=…` +

Explanation:

* *key* = the login key +
* *reference* = the reference of a shipment +
* *account* = optionally, the account where the shipment is booked on. If not specified the account belonging to the key is used. This can be used if the shipment is booked on a child account and if you want to access this shipment via Act on Behalf function with the key of the parent account. See chapter 'Act on behalf' below for more information.

=== Accounts hierarchy
Accounts are hierarchical, meaning when logged in on an account it is also possible to access child accounts. This is reflected on the interface by specifying the account on which the action should take place. Trying to access another account will be denied with an http status 'UNAUTHORIZED'.
This accounts hierarchy also applies to the accounts settings so any setting specified on an account is also applicable for the child accounts.

=== Act on Behalf

The 'Act on Behalf' feature of the API makes it possible to use a child or grandchild account in the same way as the account where you are logged into, which we call the main or (grand)parent account. Note that a child account is also sometimes referred to as a subaccount. Both terms mean the same. You can perform the same actions on the child account as which you can do on the logged in main account. This can be done by replacing the account code in the URL by the account code that you want the action to be performed on. 

Example of booking a shipment in the main account: +
1. You log in as a user of main account "DEMO" +
2. You perform a booking with this URL: `POST request to /v2/shipments/*DEMO*/BOOK` +
3. This will book the shipment on account "DEMO" + 

Example of booking a shipment in the child account: +
Now for example, account "DEMOSUB" is a child account of "DEMO". If you want to book on account "DEMOSUB" the flow is: +
1. You log in as a user of main account "DEMO" (so the same user as above which is a user that only exists in the main account). +
2. You perform a booking with this URL: `POST request to /v2/shipments/*DEMOSUB*/BOOK` +
3. This wil book the shipment on account "DEMOSUB" +

NOTE: The <<_7_9_get_account_information,Account information>> endpoint provides information to which account the Act on Behalf can be performed. 


*Permissions* 

You keep the same permissions as you have on the parent account, even if the child account has less permissions.

Example: +
Your main account has Reporting permissions and you log in with an user with Reporting permissions. 
The child account does not have Reporting permissions which means that users that directly connect to that account will not be able to download a report. If the user that logs into the main account uses Act on Behalf to log into the child account, that user will be able to download a report for that child account.

=== Reported errors
Depending on the error there are three type of error structures that can be returned. For instance, in the error response of a booking call, all three structures are possible so you need to be sure you can handle all three types. 

Normal error:
[source,json]
----
{
    "status": "BAD_REQUEST",
    "timestamp": "2024-02-29T12:42:49.450320273",
    "code": "TS222122",
    "message": "Failed to print",
    "description": "No printer found for type: LASER",
}
----
Validation errors:
[source,json]
----
{
    "status": "BAD_REQUEST",
    "timestamp": "2024-02-29T12:42:49.450320273",
    "code": "TS10002",
    "message": "Invalid input shipment data",
    "details": [{
            "reference": "this_reference_is_too_long_so_an_error_will_be_reported",
            "validationErrors": [{
                    "object": "Shipment",
                    "field": "reference",
                    "rejectedValue": "this_reference_is_too_long_so_an_error_will_be_reported",
                    "message": "size must be between 1 and 32"
                }, {
                    "object": "Shipment",
                    "field": "carrier",
                    "rejectedValue": "too_long_carrier",
                    "message": "Carrier must be 3 characters"
                }
            ]
        }
    ]
}
----

Errors with detail information:
[source,json]
----
{
    "status": "BAD_REQUEST",
    "timestamp": "2024-02-29T12:42:49.450320273",
    "code": "TS10002",
    "message": "Batch booking error",
    "description": "Booking failed for all shipments",
    "details": [{
            "errorCode": "TS222122",
            "errorDescription": "Shipment with reference 12345 already exists with status LABL and cannot be changed.",
            "errorTitle": "Batch booking failed"
        }
    ]

}
----

---
This introduction has mainly introduced the Transsmart API, described how this documentation may be used and established some conventions adopted by the Transsmart API.

The next section describes the API, by defining the resources it offers, how they may be used and their respective behaviour (normal and in error).

NOTE: From this point on-words, where used in this documentation, the "API" refers to and implies the Transsmart API. Also where used within this documentation, the "platform" is in reference to the Transsmart platform.

include::v2/v2_doc.adoc[]

